version: "3"

volumes:
  clickhouse-server-data: {}

services:
  clickhouse-server:
    image: yandex/clickhouse-server:19.13.3.26
    volumes:
      - clickhouse-server-data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  clickhouse-tabix-ui:
    image: spoonest/clickhouse-tabix-web-client:stable
    depends_on:
      - clickhouse-server
    links:
     - clickhouse-server
    ports:
     - 8080:80
